//
// Created by andru on 2/29/2020.
//

#ifndef S3_C_STRUCTURES_AND_POINTERS_TO_STRUCTURES_H
#define S3_C_STRUCTURES_AND_POINTERS_TO_STRUCTURES_H

#endif //S3_C_STRUCTURES_AND_POINTERS_TO_STRUCTURES_H

int main_StructuresandPointers();